name: magazine_api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.6
  frontend_server_client: ^2.1.3
  mysql1: ^0.20.0
  mysql_client: ^0.0.25
  shelf: ^1.4.0
  shelf_static: ^1.1.1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
  build_runner: ^2.3.0
  build_web_compilers: ^3.2.6
